# Generated by Django 6.0.1 on 2026-02-03 04:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(db_index=True, max_length=100)),
                ('user_identifier', models.CharField(default='anonymous', help_text="User ID or 'anonymous'", max_length=100)),
                ('request_payload', models.TextField(blank=True, help_text='Stored for debugging, consider privacy implications', null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], db_index=True, max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'AI Service Log',
                'verbose_name_plural': 'AI Service Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'service_name'], name='ai_services_timesta_4b501c_idx'), models.Index(fields=['status', 'service_name'], name='ai_services_status_ac4f7b_idx')],
            },
        ),
    ]
